# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45546c9a7181710d5309900e1a2b626a43aacf99d1cb69e0e94374afcf6d07a437d222a2e865debee4cfd351687b4386710eab922dbeb7c57ce085eacdf04f88

test:
  secret_key_base: afcbb8d9a6606eb6ea7cf6766506f6ef55bcd2b8030da1a3e44b2719e0154f5fc66935d42a790db26813ad9a9a507ea2731075e7ed7651acefa44d268e4c9c2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
